on: [push, pull_request]
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      PHP_INI_VALUES: assert.exception=1, zend.assertions=1
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2, phpcs
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run linter
        run: composer lint

      - name: Run tests
        run: composer test
